;	this assembly file generated by compiler
	extern __bootstrap
	extern __ARGC__
	extern __ARGV__
segment .text
global _start
_start:
	call __bootstrap
	mov rax, 3
	mov [a], rax
	mov rax, 4
	mov [b], rax
	; exit
	mov rax, 60
	xor rdi, rdi
	syscall
segment .bss
	a resb 8
	b resb 8
segment .data
	buffer_1IGIi dq 0