;	this assembly file generated by compiler
	extern puts
	extern __bootstrap
	extern __esModule
	extern __ARGC__
	extern __ARGV__
	extern char_to_int
segment .text
global _start
_start:
	call __bootstrap
	; ------ funccall -> puts
	mov rax, str_tpFA6dYwRt
	mov rdi, rax
	sub rsp, 16
	mov rax, 0
	call puts
	add rsp, 16
	; ------ funccall end -> puts
	; exit
	mov rax, 60
	xor rdi, rdi
	syscall
segment .bss
segment .data
	buffer_qYONL dq 0
	str_tpFA6dYwRt db `hello`,0