;	this assembly file generated by compiler
	extern printf
	extern __bootstrap
	extern __ARGC__
	extern __ARGV__
	extern char_to_int
	extern int_to_doub
segment .text
global _start
_start:
	call __bootstrap
	; ------ funccall -> printf
	mov rax, str_bDEu26qSSH
	mov rdi, rax
	sub rsp, 16
	mov rax, 0
	call printf
	add rsp, 16
	; ------ funccall end -> printf
	; exit
	mov rax, 60
	xor rdi, rdi
	syscall
segment .bss
segment .data
	buffer_KCYAw dq 0
	str_bDEu26qSSH db `hello\n`,0